### ISSUE TITLE
feature: choose which GPUs should swap

### ISSUE THREAD

**Issue by kirapwn** [billiford/procswap#10]
When using PC on a daily basis I want to have my GPU for games when I run them. This works fine, but what if I have 3 GPUs from which only one can be used for gaming (well maybe two if some kind of SLI). 

Would be really awesome if I can stop miner on given GPUs rather then stopping it totally.
Other cards can continue mining while I play on one of the 'main" cards.

**Comment by billiford** [comment]
I think we could solve this with settings in your mining config. I haven't done too much research into this though. What miner are you using?

Hypothetically, we could set two batch files, one that will always run on GPUs that you won't be using for gaming, and one that mines only using your gaming GPU.

**Comment by billiford** [comment]
@kirapwn I will be closing this issue as I believe you can solve this using multiple mining configs and defining which will run and startup and which will be "swap" processes in procswap.

If you have any questions or would like to share your solution and mining configs, please reopen the issue.
