### ISSUE TITLE
Blacklist programs

### ISSUE THREAD

**Issue by paypur** [billiford/procswap#11]
![image](https://user-images.githubusercontent.com/56857162/110268104-fdbf3580-7f75-11eb-91b8-3608650611a4.png)
There should be a way to blacklist certain executables from being proritized.

**Comment by billiford** [comment]
I'll add a `--ignore` flag to do just this. I'll try to release within a couple days.

**Comment by billiford** [comment]
@paypur [Release v0.4.0](https://github.com/billiford/procswap/releases/tag/v0.4.0) adds support for the `--ignore` flag which will allow you to do this.

Example command
```cmd
procswap.exe --priority D:\Steam\steamapps\common --swap C:\Mining\PhoenixMiner\start_miner.bat --ignore "python.exe"
```
You can pass in as many ignores as you want
```cmd
procswap.exe ... --ignore "python.exe" --ignore "Hades.exe"
```
You'll see a log at startup that a given `.exe` was ignored. It's not case sensitive, so passing in `--ignore "hades.exe"` will ignore both `Hades.exe` and `hades.exe`.

<img width="739" alt="procswap-v0 4 0" src="https://user-images.githubusercontent.com/7597848/110416010-f6c12180-8060-11eb-9037-8e3f5a4c435c.png">

Let me know if it works for you.

**Comment by billiford** [comment]
@paypur I will be closing this issue as I believe it is resolved. If v0.4.0 does not work for you or you have any questions, please reopen the issue.
