### ISSUE TITLE
Feature request: Minimize to tray

### ISSUE THREAD

**Issue by george7979** [billiford/procswap#14]
It would be great to have the option to start program minimized to tray.

**Comment by billiford** [comment]
Hey @george7979,

Which program are you referring to? Are you referring to the command prompt that Procswap runs in or some process that Procswap kicks off (swap process)?

**Comment by george7979** [comment]
The main program window only, not triggered processes. The triggered processes are hidden by default and this is ok.

**Comment by billiford** [comment]
I think this should be possible just using Windows' capabilities. Are you starting Procswap using a Task in Windows Task Scheduler or are you clicking on some batch script to run it? (or something else)

**Comment by george7979** [comment]
I've been using shell commands to run the procswap task minimized to the taskbar. I'll find the switch to run it not minimized to taskbar, but minimized to tray, if it exists. Good idea.

**Comment by billiford** [comment]
Hmm, I'm not sure if that switch exists (it may, haven't looked), but I'm sure something exists to run it completely in the background, but this is probably not what you want for debugging reasons.

I'm glad you brought this up though, I'll be changing the labels from `enhancement` to `good first issue` so new users can look at how others start Procswap.

I would recommend just creating a Task in Windows Task Scheduler that runs whenever you log in to start procswap. That way you don't have to do anything.

I have attached a zip file which contains my Task that you can just import. You will need to change the directory of the batch script that is ran of course, which is currently `C:\Mining\procswap\start.bat` and has the following contents
```bat
@echo off
C:\Mining\procswap\procswap.exe -p D:\Steam\steamapps\common -s C:\Mining\PhoenixMiner\start_miner.bat
```
I'll leave the issue open for a few days unless you want to go ahead and close it. Find what works best for you and please detail it here.

[ProcSwap.zip](https://github.com/billiford/procswap/files/6292429/ProcSwap.zip)

**Comment by george7979** [comment]
I have got this fully automated. I'm using scheduler to execute shell command which triggers procswap shell script to run procswap.bat minimized. It's because You cannot run bat file directly from windows shell.

Step1: create the file procswap.ps1 containing the line:
Start-Process C:\procswap\procswap.bat -WindowStyle Minimized

Step2: create task in windows scheduler:
powershell.exe -noprofile -executionpolicy bypass -file C:\procswap\procswap.ps1

This way You can start procswap.bat file minimized to taskbar, but not to tray ;).

**Comment by billiford** [comment]
Very nice! I didn't think of using PowerShell. I'll go ahead and close this.

**Comment by george7979** [comment]
The point is to replace "-WindowStyle Minimized" switch to something else, which can minimize the procswap window to taskbar.

**Comment by billiford** [comment]
Sorry, I'll reopen for now since this isn't resolved.

**Comment by billiford** [comment]
Maybe take a look at this https://stackoverflow.com/q/42928419/3878752

**Comment by billiford** [comment]
Here's Microsoft's documentation on [ProcessWindowsStyle](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processwindowstyle?view=net-5.0). You can try `Hidden` but I'm not sure if that would provide the best user experience.

**Comment by billiford** [comment]
Closing this as it seems a limitation within Windows and not something we can fix without creating a full application.

If you find anything that works for you please feel free to comment on the issue.
