### ISSUE TITLE
Doesn't directly work with Windows Store games

### ISSUE THREAD

**Issue by uncreativedan** [billiford/procswap#20]
Truly an amazing program, thank you. There may not be anything that can be done about this. Windows Store game exes are stored in the C:\Program Files\WindowsApps folder which even the administrator can't look at the files. Procswap says it can't "walk" the directory, even when run as administrator. The workaround is I made a folder to scan which has zero-byte files with game exe names in them that I created. At the very least I'm curious if there's better way of doing it.

**Comment by billiford** [comment]
It seems to be working fine for me in an Administrator Command Prompt.

First, is this the error you're seeing? I ran this in a normal command prompt:
```
C:\Mining\procswap>procswap.exe -p "C:\Program Files\WindowsApps" -s C:\Mining\xmrig-6.12.2\start.cmd

2022/02/06 - 06:37:00 | INFO  | setup searching C:\Program Files\WindowsApps for executables
2022/02/06 - 06:37:00 | ERROR | setup error searching C:\Program Files\WindowsApps for executables: error walking C:\Program Files\WindowsApps searching for .exes: open C:\Program Files\WindowsApps: Access is denied.
```
In an admin command prompt it seemed to scan just fine though.
```
C:\Mining\procswap>procswap.exe -p "C:\Program Files\WindowsApps" -s C:\Mining\xmrig-6.12.2\start.cmd

2022/02/06 - 06:35:29 | INFO  | setup searching C:\Program Files\WindowsApps for executables
2022/02/06 - 06:35:30 | INFO  | setup found 133 priority executables
```
Please provide a screenshot of the problem if possible.

**Comment by uncreativedan** [comment]
Thanks for your response but it looks like I was getting mixed up. I had two ways to start the batch file as I was mess about and it was not the admin one when I was trying it last. It works fine.
